
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightPOWrightUMINUSleftTIMESDIVIDEleftPLUSMINUSDIVIDE FRACTION LPAREN MINUS NUMBER PLUS POW RPAREN TIMESexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expression\n                  | expression POW expressionexpression : LPAREN expression RPARENexpression : MINUS expression %prec UMINUSexpression : NUMBER\n                  | FRACTION'
    
_lr_action_items = {'LPAREN':([0,2,3,6,7,8,9,10,],[3,3,3,3,3,3,3,3,]),'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,],[2,7,2,2,-8,-9,2,2,2,2,2,7,7,-1,-2,7,7,7,-6,]),'NUMBER':([0,2,3,6,7,8,9,10,],[4,4,4,4,4,4,4,4,]),'FRACTION':([0,2,3,6,7,8,9,10,],[5,5,5,5,5,5,5,5,]),'$end':([1,4,5,11,13,14,15,16,17,18,],[0,-8,-9,-7,-1,-2,-3,-4,-5,-6,]),'PLUS':([1,4,5,11,12,13,14,15,16,17,18,],[6,-8,-9,6,6,-1,-2,6,6,6,-6,]),'TIMES':([1,4,5,11,12,13,14,15,16,17,18,],[8,-8,-9,8,8,-1,-2,-3,-4,8,-6,]),'DIVIDE':([1,4,5,11,12,13,14,15,16,17,18,],[9,-8,-9,9,9,-1,-2,-3,-4,9,-6,]),'POW':([1,4,5,11,12,13,14,15,16,17,18,],[10,-8,-9,-7,10,-1,-2,-3,-4,10,-6,]),'RPAREN':([4,5,11,12,13,14,15,16,17,18,],[-8,-9,-7,18,-1,-2,-3,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,6,7,8,9,10,],[1,11,12,13,14,15,16,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','lexpar.py',51),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','lexpar.py',52),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','lexpar.py',53),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','lexpar.py',54),
  ('expression -> expression POW expression','expression',3,'p_expression_binop','lexpar.py',55),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','lexpar.py',77),
  ('expression -> MINUS expression','expression',2,'p_expression_negative','lexpar.py',81),
  ('expression -> NUMBER','expression',1,'p_expression_valueue','lexpar.py',85),
  ('expression -> FRACTION','expression',1,'p_expression_valueue','lexpar.py',86),
]
